# Site settings
title: Gabo
email: jorge@puentesarr.in
description: El sitio de Gabo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabo.puentesarr.in" # the base hostname & protocol for your site
twitter_username: puentesarrin
github_username:  puentesarrin

# Build settings
markdown: kramdown
